EXPERIMENT:
  NAME: ""
  TAG: "cd_sdd_dkd,res50_sdd,shv1_sdd"
  PROJECT: "cifar100_baselines_gamma8"
DISTILLER:
  TYPE: "CD_SDD_DKD"
  TEACHER: "ResNet50_sdd"
  STUDENT: "ShuffleV1_sdd"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

