EXPERIMENT:
  NAME: ""
  TAG: "SDD_NKD,wrn_40_2_sdd,shuv1_sdd"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SDD_NKD"
  TEACHER: "wrn_40_2_sdd"
  STUDENT: "ShuffleV1_sdd"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

