EXPERIMENT:
  NAME: ""
  TAG: "CD_SDD_NKD,wrn_40_2_sdd,mv2_sdd"
  PROJECT: "cifar100_baselines_gamma2"
DISTILLER:
  TYPE: "CD_SDD_NKD"
  TEACHER: "wrn_40_2_sdd"
  STUDENT: "MobileNetV2_sdd"
SOLVER:
  BATCH_SIZE: 64  # 64->512
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

DKD:
  BETA: 6.0